### ISSUE TITLE
Wrong parameter syntax for uglify-js.

### ISSUE THREAD

**Issue by ShrykeWindgrace** [cachix/elm2nix#38]
This issue is related to #37. If I switch the collection to `nodePackages` instead of `nodePackages_10_x`, then building js output fails because of `--output=/path/to/output/file.min.js` syntax.

If I switch to `--output /path/to/output/file.min.js` (note that there is no `=` sign), the uglification/minification seems to be ok.

**Comment by turboMaCk** [comment]
this was fixed in https://github.com/cachix/elm2nix/pull/40 but there is no new release of elm2nix - you can use master in meantime though.

**Comment by ShrykeWindgrace** [comment]
@turboMaCk  thanks for info, will do that!

**Comment by domenkozar** [comment]
released 0.2.1
