### ISSUE TITLE
Snapshot only outputs any data when redirected to the registry.dat file

### ISSUE THREAD

**Issue by tad-lispy** [cachix/elm2nix#43]
Hey! Thanks for your work on elm2nix. 

Today I've run into an unexpected and confusing behaviour. It's easier to show than explain. Consider this:

```plain
$ elm2nix snapshot # output is empty

$ echo $? # but no error
0

$ elm2nix snapshot > something-else.dat

$ hexdump something-else.dat # again empty

$ elm2nix snapshot > registry.dat 

$ hexdump registry.dat # now it works!
0000000 0000 0000 0000 702c 0000 0000 0000 ae08
0000010 3003 6975 6511 6d6c 742d 7361 2d6b 6170
0000020 6172 6c6c 6c65 0002 0000 0000 0000 0000
[...]
```
My Haskell is rather bad, but I think it has something to do with this line:

https://github.com/cachix/elm2nix/blob/239a5ecf317f3aecc0d147a43aa74f2222b6fd64/src/Elm2Nix/PackagesSnapshot.hs#L157

**Comment by tad-lispy** [comment]
I'm not sure if I made myself clear. The issue is that it's not possible to output to any other file than `registry.dat`. IMO it's bad in itself - I'd prefer to use other, more meaningful name, like `elm-registry.dat`. But if only this single name is allowed, then what is the redirection for? Since the path is essentially hardcoded, why not make the program just create this file? Why do I need to redirect?

I think a solution could be to make `registry.dat` the default, drop the requirement to redirect and add an option like `--output=<path>` so that user could choose a different name. So:

```sh
elm2nix snapshot # creates registry.dat
elm2nix snapshot --output=elm-registry.dat # creates elm-registry.dat
```

**Comment by TLATER** [comment]
The docs are actually wrong, `elm2nix snapshot` currently doesn't output anything to stdout, but simply creates a file named `registry.dat`.

The redirected output just ends up creating an empty file. This is a documentation bug (though also the usability bug you describe).

**Comment by bmillwood** [comment]
I think with the doc updates this issue seems already OK to close to me, but if it's waiting for `snapshot` getting the option to specify the output path, I've added that in #54

**Comment by domenkozar** [comment]
Since #54 you can control where to write the file and it should become much smaller and won't change on each invocation.
