### ISSUE TITLE
following readme steps verbatim deploys broken app

### ISSUE THREAD

**Issue by goosetherumfoodle** [cachix/elm2nix#50]
It's fair if you want to declare that this is an issue with todomvc and not you, but right now just doing the steps in the readme:

```
git clone https://github.com/evancz/elm-todomvc.git
cd elm-todomvc
elm2nix init > default.nix
elm2nix convert > elm-srcs.nix
elm2nix snapshot > versions.dat
nix-build
chromium ./result/Main.html
```

deploys a broken app with an `Initialization Error`. Seems to be the same problem referred to here: https://github.com/evancz/elm-todomvc/issues/67 but following those steps didn't fix the issue for me.

**Comment by clushie** [comment]
Hey the README was outdated, does this #51 work for you?

**Comment by goosetherumfoodle** [comment]
Looks good. Thanks @clushie !
